### ISSUE TITLE
static_caching.php is updated after git commits when paired with git functionality

### ISSUE THREAD

**Issue by AdD959** [aerni/statamic-dynamic-cache#4]
Hi Michael, 

I'm not 100% sure about whether to open an issue for this so apologies if its not appropriate. I noticed that when using statamics git commit/push functionality alongside your addon (which is super helpful by the way, thank you), the automatic changes made to static_caching.php occur _after_ git commits/pushes changes. I would think that these changes should occur before by default.

Adam

**Comment by aerni** [comment]
This addon depends on certain Statamic events to fire before it can determine what changes to save to the `static_caching` config file. That's why the config is changed after the content has been committed. There is no way around this.

However, I might be able to add a custom event that triggers another git commit. I have to look into this.

**Comment by aerni** [comment]
Just tagged [v1.1.0](https://github.com/aerni/statamic-dynamic-cache/releases/tag/v1.1.0) which adds support for the Git integration.

**Comment by AdD959** [comment]
Amazing, just tried it out and it works perfectly :)
